import fs from "node:fs";
import path from "node:path";

import { logSchoologyApiRequest } from "@/lib/schoology/apiLog";
import { buildOAuth1AuthorizationHeader } from "@/lib/schoology/oauth1";
import {
  buildSchoologyApiUrl,
  getSchoologyApiBase,
  getSchoologyAppConfig,
  normalizeSchoologyWebDomain,
  SCHOOLOGY_API_HOST,
  SCHOOLOGY_WEB_DOMAIN_DEFAULT,
} from "@/lib/schoology/config";
import { SchoologyConfigError } from "@/lib/schoology/errors";

export const DIAGNOSTIC_REPORT_PATH = path.join(
  process.cwd(),
  "data",
  "schoology-debug-report.json",
);

const USER_AGENT = "ollm-assessment-assistant/1.0";

export type SchoologyResponseKind =
  | "OK"
  | "CLOUDFRONT_WAF"
  | "HTML_404"
  | "JSON_API_ERROR"
  | "OTHER_ERROR";

export type SchoologyDiagnosticVerdict =
  | "PASS"
  | "FAIL_CONFIG"
  | "FAIL_API_AUTH"
  | "FAIL_API_PERMISSION";

export type DiagnosticStep = {
  id: string;
  ok: boolean;
  data?: Record<string, unknown>;
  diagnosis?: string;
  error?: string;
};

export type SchoologyDiagnosticReport = {
  generatedAt: string;
  verdict: SchoologyDiagnosticVerdict;
  summary: string;
  authMode: "two-legged";
  steps: DiagnosticStep[];
  recommendedFixes: string[];
};

export function prefixSecret(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    return "(empty)";
  }
  if (trimmed.length <= 6) {
    return `${trimmed.slice(0, 2)}…`;
  }
  return `${trimmed.slice(0, 6)}…`;
}

export function classifySchoologyResponse(
  status: number,
  body: string,
): SchoologyResponseKind {
  const lower = body.toLowerCase();

  if (status >= 200 && status < 300) {
    return "OK";
  }

  if (
    lower.includes("generated by cloudfront") ||
    lower.includes("request blocked")
  ) {
    return "CLOUDFRONT_WAF";
  }

  if (
    status === 404 &&
    (lower.includes("<!doctype") || lower.includes("<html") || lower.includes("page not found"))
  ) {
    return "HTML_404";
  }

  const trimmed = body.trim();
  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    return "JSON_API_ERROR";
  }

  return "OTHER_ERROR";
}

export function buildAuthFailureMessage(status: number, body: string): string {
  const kind = classifySchoologyResponse(status, body);
  const snippet = body.replace(/\s+/g, " ").slice(0, 200);

  if (kind === "CLOUDFRONT_WAF") {
    return (
      "Schoology blocked the request (CloudFront 403). " +
      "Verify SCHOOLOGY_CONSUMER_KEY and SCHOOLOGY_CONSUMER_SECRET."
    );
  }

  if (snippet) {
    return `Schoology API auth failed (${status}): ${snippet}`;
  }

  return `Schoology API auth failed (${status}). Check your API credentials and permissions.`;
}

type ApiProbeResult = {
  ok: boolean;
  status: number;
  kind: SchoologyResponseKind;
  bodySnippet: string;
  body: string;
};

async function probeApiEndpoint(path: string): Promise<ApiProbeResult> {
  const config = getSchoologyAppConfig();
  const url = buildSchoologyApiUrl(path);
  const authorization = buildOAuth1AuthorizationHeader({
    method: "GET",
    url,
    consumerKey: config.consumerKey,
    consumerSecret: config.consumerSecret,
  });
  logSchoologyApiRequest("GET", url, authorization);

  const response = await fetch(url, {
    method: "GET",
    headers: {
      Authorization: authorization,
      Accept: "application/json",
      "User-Agent": USER_AGENT,
    },
    redirect: "manual",
  });

  const body = await response.text().catch(() => "");
  const kind = classifySchoologyResponse(response.status, body);

  return {
    ok: response.ok,
    status: response.status,
    kind,
    bodySnippet: body.replace(/\s+/g, " ").slice(0, 200),
    body,
  };
}

function parseUserIdFromAppUserInfoResponse(body: string): string | undefined {
  try {
    const data = JSON.parse(body) as { api_uid?: string | number };
    const id = data.api_uid;
    return id != null ? String(id) : undefined;
  } catch {
    return undefined;
  }
}

function buildRecommendedFixes(verdict: SchoologyDiagnosticVerdict, steps: DiagnosticStep[]): string[] {
  const fixes: string[] = [];

  const apiAuthStep = steps.find((s) => s.id === "api_auth");
  const bodySnippet = String(apiAuthStep?.data?.bodySnippet ?? "");

  if (bodySnippet.includes("not authorized to make 2-legged")) {
    fixes.push(
      "These credentials are from a Schoology Platform App (three-legged only). " +
        "For this MVP, request personal two-legged API keys at Schoology → Integration → API (/api).",
    );
  }

  if (verdict === "FAIL_CONFIG") {
    fixes.push(
      "Set SCHOOLOGY_CONSUMER_KEY and SCHOOLOGY_CONSUMER_SECRET in .env.local (not placeholders).",
    );
    fixes.push("Use two-legged API keys from Schoology → Integration → API (or your admin).");
    fixes.push("Restart the dev server after changing .env.local.");
  }

  if (verdict === "FAIL_API_AUTH") {
    fixes.push("Verify consumer key/secret and that the key owner has API access enabled.");
    fixes.push("Confirm SCHOOLOGY_BASE_URL=https://api.schoology.com/v1");
  }

  if (verdict === "FAIL_API_PERMISSION") {
    fixes.push("Check API permissions for the key owner (teacher/section access).");
  }

  return fixes;
}

function determineVerdict(steps: DiagnosticStep[]): SchoologyDiagnosticVerdict {
  const byId = Object.fromEntries(steps.map((s) => [s.id, s]));

  if (!byId.config?.ok) return "FAIL_CONFIG";
  if (!byId.api_auth?.ok) return "FAIL_API_AUTH";
  if (byId.api_permissions && !byId.api_permissions.ok) return "FAIL_API_PERMISSION";

  return "PASS";
}

function buildSummary(verdict: SchoologyDiagnosticVerdict): string {
  switch (verdict) {
    case "PASS":
      return "Two-legged API config and authenticated calls look healthy.";
    case "FAIL_CONFIG":
      return "Schoology environment configuration is incomplete or invalid.";
    case "FAIL_API_AUTH":
      return "GET /app-user-info failed — check SCHOOLOGY_CONSUMER_KEY and SCHOOLOGY_CONSUMER_SECRET.";
    case "FAIL_API_PERMISSION":
      return "Authenticated but section access failed — check API permissions.";
    default:
      return "Schoology diagnostics completed.";
  }
}

export async function runSchoologyDiagnostics(): Promise<SchoologyDiagnosticReport> {
  const steps: DiagnosticStep[] = [];

  const consumerKey = process.env.SCHOOLOGY_CONSUMER_KEY?.trim() ?? "";
  const consumerSecret = process.env.SCHOOLOGY_CONSUMER_SECRET?.trim() ?? "";
  const baseUrlRaw = process.env.SCHOOLOGY_BASE_URL?.trim() || "(default)";
  const domainRaw = process.env.SCHOOLOGY_DOMAIN?.trim() || "";

  const configIssues: string[] = [];
  let apiBase = "";
  try {
    apiBase = getSchoologyApiBase();
  } catch (err) {
    configIssues.push(
      err instanceof SchoologyConfigError
        ? err.message
        : "SCHOOLOGY_BASE_URL is invalid.",
    );
  }

  if (!consumerKey || consumerKey.includes("your_consumer_key")) {
    configIssues.push("SCHOOLOGY_CONSUMER_KEY is missing or still a placeholder.");
  }
  if (!consumerSecret || consumerSecret.includes("your_consumer_secret")) {
    configIssues.push("SCHOOLOGY_CONSUMER_SECRET is missing or still a placeholder.");
  }

  const webDomain = normalizeSchoologyWebDomain(domainRaw || SCHOOLOGY_WEB_DOMAIN_DEFAULT);

  steps.push({
    id: "config",
    ok: configIssues.length === 0,
    data: {
      authMode: "two-legged",
      apiBaseUrl: apiBase || "(invalid)",
      apiHostname: SCHOOLOGY_API_HOST,
      apiBaseUrlRaw: baseUrlRaw,
      webDomain,
      consumerKeyPrefix: prefixSecret(consumerKey),
    },
    ...(configIssues.length > 0
      ? { error: configIssues.join(" "), diagnosis: "INVALID_CONFIG" }
      : { diagnosis: "OK" }),
  });

  if (configIssues.length > 0) {
    const verdict = "FAIL_CONFIG";
    return {
      generatedAt: new Date().toISOString(),
      verdict,
      summary: buildSummary(verdict),
      authMode: "two-legged",
      steps,
      recommendedFixes: buildRecommendedFixes(verdict, steps),
    };
  }

  try {
    getSchoologyAppConfig();
  } catch (err) {
    const message =
      err instanceof SchoologyConfigError ? err.message : "Failed to load Schoology config.";
    steps[0] = { ...steps[0], ok: false, error: message, diagnosis: "CONFIG_ERROR" };
    const verdict = "FAIL_CONFIG";
    return {
      generatedAt: new Date().toISOString(),
      verdict,
      summary: buildSummary(verdict),
      authMode: "two-legged",
      steps,
      recommendedFixes: buildRecommendedFixes(verdict, steps),
    };
  }

  const authProbe = await probeApiEndpoint("/app-user-info");
  steps.push({
    id: "api_auth",
    ok: authProbe.ok,
    data: {
      path: "/app-user-info",
      status: authProbe.status,
      kind: authProbe.kind,
      bodySnippet: authProbe.bodySnippet,
      oauthSignatureMethod: "PLAINTEXT",
    },
    diagnosis: authProbe.ok ? "OK" : authProbe.kind,
    ...(authProbe.ok ? {} : { error: `GET /app-user-info returned HTTP ${authProbe.status}.` }),
  });

  if (authProbe.ok) {
    const userId = parseUserIdFromAppUserInfoResponse(authProbe.body);
    if (userId) {
      const sectionsProbe = await probeApiEndpoint(`/users/${userId}/sections`);
      steps.push({
        id: "api_permissions",
        ok: sectionsProbe.ok,
        data: {
          path: `/users/${userId}/sections`,
          status: sectionsProbe.status,
          kind: sectionsProbe.kind,
          bodySnippet: sectionsProbe.bodySnippet,
        },
        diagnosis: sectionsProbe.ok ? "OK" : sectionsProbe.kind,
        ...(sectionsProbe.ok
          ? {}
          : { error: `GET /users/${userId}/sections returned HTTP ${sectionsProbe.status}.` }),
      });
    }
  }

  const verdict = determineVerdict(steps);

  return {
    generatedAt: new Date().toISOString(),
    verdict,
    summary: buildSummary(verdict),
    authMode: "two-legged",
    steps,
    recommendedFixes: buildRecommendedFixes(verdict, steps),
  };
}

function ensureDataDir(): void {
  const dataDir = path.join(process.cwd(), "data");
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }
}

export function writeDiagnosticReport(report: SchoologyDiagnosticReport): string {
  ensureDataDir();
  fs.writeFileSync(DIAGNOSTIC_REPORT_PATH, JSON.stringify(report, null, 2), "utf8");
  return DIAGNOSTIC_REPORT_PATH;
}

export function formatDiagnosticReportForConsole(report: SchoologyDiagnosticReport): string {
  const lines = [
    `Schoology diagnostics — ${report.verdict} (${report.authMode})`,
    report.summary,
    "",
  ];

  for (const step of report.steps) {
    const status = step.ok ? "OK" : "FAIL";
    lines.push(`  [${status}] ${step.id}`);
    if (step.error) {
      lines.push(`         ${step.error}`);
    }
  }

  if (report.recommendedFixes.length > 0) {
    lines.push("");
    lines.push("Recommended fixes:");
    for (const fix of report.recommendedFixes) {
      lines.push(`  • ${fix}`);
    }
  }

  lines.push("");
  lines.push(`Report written to ${DIAGNOSTIC_REPORT_PATH}`);

  return lines.join("\n");
}
